"""collab suite: notes, priority, macros, contact notes

Revision ID: cf845e8846e5
Revises: d3f9c598d7eb
Create Date: 2026-07-18 10:27:11.949347
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf845e8846e5'
down_revision: str | None = 'd3f9c598d7eb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macros',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('visibility', sa.String(length=10), nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macros_workspace_id'), 'macros', ['workspace_id'], unique=False)
    op.create_table('contact_notes',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_notes_contact_id'), 'contact_notes', ['contact_id'], unique=False)
    op.create_index(op.f('ix_contact_notes_workspace_id'), 'contact_notes', ['workspace_id'], unique=False)
    op.add_column('chats', sa.Column('priority', sa.String(length=10), nullable=True))
    # server_default so the NOT NULL add succeeds on the live messages table
    op.add_column('messages', sa.Column('is_private', sa.Boolean(), nullable=False,
                                        server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_private')
    op.drop_column('chats', 'priority')
    op.drop_index(op.f('ix_contact_notes_workspace_id'), table_name='contact_notes')
    op.drop_index(op.f('ix_contact_notes_contact_id'), table_name='contact_notes')
    op.drop_table('contact_notes')
    op.drop_index(op.f('ix_macros_workspace_id'), table_name='macros')
    op.drop_table('macros')
    # ### end Alembic commands ###
